/*
*   GPLGEN+, An improvement on GPLGEN, a GPL license/header generator 
*   Copyright (C) 2024 Lilly H. St Claire
*            This program is free software: you can redistribute it and/or modify
*            it under the terms of the GNU General Public License as published by
*            the Free Software Foundation, either version 3 of the License, or (at
*            your option) any later version.
*            This program is distributed in the hope that it will be useful, but
*            WITHOUT ANY WARRANTY; without even the implied warranty of
*            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*            General Public License for more details.
*            You should have received a copy of the GNU General Public License
*            along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef X__GPLGENP_LICENSE_H__X
#define X__GPLGENP_LICENSE_H__X
#include <stdio.h>

static void gplp_license_fprint_license(FILE *fp) {
       fprintf(fp, "GNU General Public License\n");
       fprintf(fp, "Version 3, 29 June 2007\n");
       fprintf(fp, "            Copyright (c) 2007 Free Software Foundation, Inc. <https://www.fsf.org>\n\n");
       fprintf(fp, "            Everyone is permitted to copy and distribute verbatim copies of this\n");
       fprintf(fp, "            license document, but changing it is not allowed.\n\n");
       fprintf(fp, "Preamble\n");
       fprintf(fp, "    The GNU General Public License is a free, copyleft license for software and other kinds\n");
       fprintf(fp, "    of works.\n\n");
       fprintf(fp, "    The licenses for most software and other practical works are designed to take away your\n");
       fprintf(fp, "    freedom to share and change the works.  By contrast, the GNU General Public License is\n");
       fprintf(fp, "    intended to guarantee your freedom to share and change all versions of a program--to\n");
       fprintf(fp, "    make sure it remains free software for all its users.  We, the Free Software\n");
       fprintf(fp, "    Foundation, use the GNU General Public License for most of our software; it applies\n");
       fprintf(fp, "    also to any other work released this way by its authors.  You can apply it to your\n");
       fprintf(fp, "    programs, too.\n\n");
       fprintf(fp, "    When we speak of free software, we are referring to freedom, not price.  Our General\n");
       fprintf(fp, "    Public Licenses are designed to make sure that you have the freedom to distribute\n");
       fprintf(fp, "    copies of free software (and charge for them if you wish), that you receive source code\n");
       fprintf(fp, "    or can get it if you want it, that you can change the software or use pieces of it in\n");
       fprintf(fp, "    new free programs, and that you know you can do these things.\n\n");
       fprintf(fp, "    To protect your rights, we need to prevent others from denying you these rights or\n");
       fprintf(fp, "    asking you to surrender the rights.  Therefore, you have certain responsibilities if\n");
       fprintf(fp, "    you distribute copies of the software, or if you modify it: responsibilities to respect\n");
       fprintf(fp, "    the freedom of others.\n\n");
       fprintf(fp, "    For example, if you distribute copies of such a program, whether gratis or for a fee,\n");
       fprintf(fp, "    you must pass on to the recipients the same freedoms that you received.  You must make\n");
       fprintf(fp, "    sure that they, too, receive or can get the source code.  And you must show them these\n");
       fprintf(fp, "    terms so they know their rights.\n\n");
       fprintf(fp, "    Developers that use the GNU GPL protect your rights with two steps: (1) assert\n");
       fprintf(fp, "    copyright on the software, and (2) offer you this License giving you legal permission\n");
       fprintf(fp, "    to copy, distribute and/or modify it.\n\n");
       fprintf(fp, "    For the developers' and authors' protection, the GPL clearly explains that there is no\n");
       fprintf(fp, "    warranty for this free software.  For both users' and authors' sake, the GPL requires\n");
       fprintf(fp, "    that modified versions be marked as changed, so that their problems will not be\n");
       fprintf(fp, "    attributed erroneously to authors of previous versions.\n\n");
       fprintf(fp, "    Some devices are designed to deny users access to install or run modified versions of\n");
       fprintf(fp, "    the software inside them, although the manufacturer can do so.  This is fundamentally\n");
       fprintf(fp, "    incompatible with the aim of protecting users' freedom to change the software.  The\n");
       fprintf(fp, "    systematic pattern of such abuse occurs in the area of products for individuals to use,\n");
       fprintf(fp, "    which is precisely where it is most unacceptable.  Therefore, we have designed this\n");
       fprintf(fp, "    version of the GPL to prohibit the practice for those products.  If such problems arise\n");
       fprintf(fp, "    substantially in other domains, we stand ready to extend this provision to those\n");
       fprintf(fp, "    domains in future versions of the GPL, as needed to protect the freedom of users.\n\n");
       fprintf(fp, "    Finally, every program is threatened constantly by software patents.  States should not\n");
       fprintf(fp, "    allow patents to restrict development and use of software on general-purpose computers,\n");
       fprintf(fp, "    but in those that do, we wish to avoid the special danger that patents applied to a\n");
       fprintf(fp, "    free program could make it effectively proprietary.  To prevent this, the GPL assures\n");
       fprintf(fp, "    that patents cannot be used to render the program non-free.\n\n");
       fprintf(fp, "    The precise terms and conditions for copying, distribution and modification follow.\n\n");
       fprintf(fp, "TERMS AND CONDITIONS\n");
       fprintf(fp, "    0. Definitions.\n");
       fprintf(fp, "        \"This License\" refers to version 3 of the GNU General Public License.\n\n");
       fprintf(fp, "        \"Copyright\" also means copyright-like laws that apply to other kinds of works, such\n");
       fprintf(fp, "        as semiconductor masks.\n\n");
       fprintf(fp, "        \"The  Program\"  refers to any copyrightable work licensed under this License.  Each\n");
       fprintf(fp, "        licensee is addressed as \"you\".  \"Licensees\" and \"recipients\" may be individuals or\n");
       fprintf(fp, "        organizations.\n\n");
       fprintf(fp, "        To \"modify\" a work means to copy from or adapt all or part of the work in a fashion\n");
       fprintf(fp, "        requiring copyright permission, other than  the  making  of  an  exact  copy.   The\n");
       fprintf(fp, "        resulting  work is called a \"modified version\" of the earlier work or a work \"based\n");
       fprintf(fp, "        on\" the earlier work.\n\n");
       fprintf(fp, "        A \"covered work\" means either the  unmodified  Program  or  a  work  based  on  the\n");
       fprintf(fp, "        Program.\n\n");
       fprintf(fp, "        To  \"propagate\" a work means to do anything with it that, without permission, would\n");
       fprintf(fp, "        make you directly or secondarily liable for infringement under applicable copyright\n");
       fprintf(fp, "        law, except executing it on a computer or modifying a  private  copy.   Propagation\n");
       fprintf(fp, "        includes  copying, distribution (with or without modification), making available to\n");
       fprintf(fp, "        the public, and in some countries other activities as well.\n\n");
       fprintf(fp, "        To \"convey\" a work means any kind of propagation that enables other parties to make\n");
       fprintf(fp, "        or receive copies.  Mere interaction with a user through a computer  network,  with\n");
       fprintf(fp, "        no transfer of a copy, is not conveying.\n\n");
       fprintf(fp, "        An  interactive  user  interface displays \"Appropriate Legal Notices\" to the extent\n");
       fprintf(fp, "        that it includes a convenient and prominently visible feature that (1) displays  an\n");
       fprintf(fp, "        appropriate  copyright notice, and (2) tells the user that there is no warranty for\n");
       fprintf(fp, "        the work (except to the extent that warranties are provided),  that  licensees  may\n");
       fprintf(fp, "        convey the work under this License, and how to view a copy of this License.  If the\n");
       fprintf(fp, "        interface  presents a list of user commands or options, such as a menu, a prominent\n");
       fprintf(fp, "        item in the list meets this criterion.\n\n");
       fprintf(fp, "    1. Source Code.\n");
       fprintf(fp, "        The \"source code\" for a work means the  preferred  form  of  the  work  for  making\n");
       fprintf(fp, "        modifications to it.  \"Object code\" means any non-source form of a work.\n\n");
       fprintf(fp, "        A  \"Standard  Interface\"  means  an  interface  that either is an official standard\n");
       fprintf(fp, "        defined by a recognized standards body, or, in the case of interfaces specified for\n");
       fprintf(fp, "        a particular programming language, one that is widely used among developers working\n");
       fprintf(fp, "        in that language.\n\n");
       fprintf(fp, "        The \"System Libraries\" of an executable work include anything, other than the  work\n");
       fprintf(fp, "        as a whole, that (a) is included in the normal form of packaging a Major Component,\n");
       fprintf(fp, "        but which is not part of that Major Component, and (b) serves only to enable use of\n");
       fprintf(fp, "        the  work with that Major Component, or to implement a Standard Interface for which\n");
       fprintf(fp, "        an implementation is available to  the  public  in  source  code  form.   A  \"Major\n");
       fprintf(fp, "        Component\",  in  this  context,  means  a major essential component (kernel, window\n");
       fprintf(fp, "        system, and so on)  of  the  specific  operating  system  (if  any)  on  which  the\n");
       fprintf(fp, "        executable  work  runs,  or  a compiler used to produce the work, or an object code\n");
       fprintf(fp, "        interpreter used to run it.\n\n");
       fprintf(fp, "        The \"Corresponding Source\" for a work in object code form means all the source code\n");
       fprintf(fp, "        needed to generate, install, and (for an executable work) run the object  code  and\n");
       fprintf(fp, "        to  modify  the  work,  including scripts to control those activities.  However, it\n");
       fprintf(fp, "        does not include the work's System Libraries, or general-purpose tools or generally\n");
       fprintf(fp, "        available free programs which are used unmodified in  performing  those  activities\n");
       fprintf(fp, "        but  which  are  not  part of the work.  For example, Corresponding Source includes\n");
       fprintf(fp, "        interface definition files associated with source  files  for  the  work,  and  the\n");
       fprintf(fp, "        source  code  for shared libraries and dynamically linked subprograms that the work\n");
       fprintf(fp, "        is specifically designed to require, such as  by  intimate  data  communication  or\n");
       fprintf(fp, "        control flow between those subprograms and other parts of the work.\n\n");
       fprintf(fp, "        The  Corresponding  Source  need  not  include  anything  that users can regenerate\n");
       fprintf(fp, "        automatically from other parts of the Corresponding Source.\n\n");
       fprintf(fp, "        The Corresponding Source for a work in source code form is that same work.\n\n");
       fprintf(fp, "    2. Basic Permissions.\n");
       fprintf(fp, "        All rights granted under this License are granted for the term of copyright on  the\n");
       fprintf(fp, "        Program,  and are irrevocable provided the stated conditions are met.  This License\n");
       fprintf(fp, "        explicitly affirms your unlimited permission to run the  unmodified  Program.   The\n");
       fprintf(fp, "        output  from  running a covered work is covered by this License only if the output,\n");
       fprintf(fp, "        given its content, constitutes a covered  work.   This  License  acknowledges  your\n");
       fprintf(fp, "        rights of fair use or other equivalent, as provided by copyright law.\n\n");
       fprintf(fp, "        You  may  make,  run  and  propagate  covered works that you do not convey, without\n");
       fprintf(fp, "        conditions so long as your license otherwise remains  in  force.   You  may  convey\n");
       fprintf(fp, "        covered  works  to  others  for  the sole purpose of having them make modifications\n");
       fprintf(fp, "        exclusively for you, or provide  you  with  facilities  for  running  those  works,\n");
       fprintf(fp, "        provided  that  you comply with the terms of this License in conveying all material\n");
       fprintf(fp, "        for which you do not control copyright.  Those thus making or running  the  covered\n");
       fprintf(fp, "        works  for  you  must  do  so  exclusively on your behalf, under your direction and\n");
       fprintf(fp, "        control, on terms that prohibit them from making any  copies  of  your  copyrighted\n");
       fprintf(fp, "        material outside their relationship with you.\n\n");
       fprintf(fp, "        Conveying  under  any  other circumstances is permitted solely under the conditions\n");
       fprintf(fp, "        stated below.  Sublicensing is not allowed; section 10 makes it unnecessary.\n\n");
       fprintf(fp, "    3. Protecting Users' Legal Rights From Anti-Circumvention Law.\n");
       fprintf(fp, "        No covered work shall be deemed part of an effective  technological  measure  under\n");
       fprintf(fp, "        any  applicable  law  fulfilling obligations under article 11 of the WIPO copyright\n");
       fprintf(fp, "        treaty adopted on 20 December 1996, or  similar  laws  prohibiting  or  restricting\n");
       fprintf(fp, "        circumvention of such measures.\n\n");
       fprintf(fp, "        When  you  convey a covered work, you waive any legal power to forbid circumvention\n");
       fprintf(fp, "        of  technological  measures  to  the  extent  such  circumvention  is  effected  by\n");
       fprintf(fp, "        exercising  rights  under  this  License  with respect to the covered work, and you\n");
       fprintf(fp, "        disclaim any intention to limit operation or modification of the work as a means of\n");
       fprintf(fp, "        enforcing, against the work's users, your or third parties' legal rights to  forbid\n");
       fprintf(fp, "        circumvention of technological measures.\n\n");
       fprintf(fp, "    4. Conveying Verbatim Copies.\n");
       fprintf(fp, "        You  may  convey verbatim copies of the Program's source code as you receive it, in\n");
       fprintf(fp, "        any medium, provided that you conspicuously and appropriately publish on each  copy\n");
       fprintf(fp, "        an  appropriate copyright notice; keep intact all notices stating that this License\n");
       fprintf(fp, "        and any non-permissive terms added in accord with section 7 apply to the code; keep\n");
       fprintf(fp, "        intact all notices of the absence of any warranty; and give all recipients  a  copy\n");
       fprintf(fp, "        of this License along with the Program.\n\n");
       fprintf(fp, "        You  may  charge  any  price or no price for each copy that you convey, and you may\n");
       fprintf(fp, "        offer support or warranty protection for a fee.\n\n");
       fprintf(fp, "    5. Conveying Modified Source Versions.\n");
       fprintf(fp, "        You may convey a work based on the Program, or the modifications to produce it from\n");
       fprintf(fp, "        the Program, in the form of source code under the terms of section 4, provided that\n");
       fprintf(fp, "        you also meet all of these conditions:\n\n");
       fprintf(fp, "        a.  The work must carry prominent notices stating that you modified it, and  giving\n");
       fprintf(fp, "            a relevant date.\n\n");
       fprintf(fp, "        b.  The  work  must  carry prominent notices stating that it is released under this\n");
       fprintf(fp, "            License and any conditions added under section 7.   This  requirement  modifies\n");
       fprintf(fp, "            the requirement in section 4 to \"keep intact all notices\".\n\n");
       fprintf(fp, "        c.  You  must license the entire work, as a whole, under this License to anyone who\n");
       fprintf(fp, "            comes into possession of a copy.  This License will therefore apply, along with\n");
       fprintf(fp, "            any applicable section 7 additional terms, to the whole of the  work,  and  all\n");
       fprintf(fp, "            its  parts,  regardless  of  how  they  are  packaged.   This  License gives no\n");
       fprintf(fp, "            permission to license the work in any other way, but  it  does  not  invalidate\n");
       fprintf(fp, "            such permission if you have separately received it.\n\n");
       fprintf(fp, "        d.  If  the  work  has  interactive  user interfaces, each must display Appropriate\n");
       fprintf(fp, "            Legal Notices; however, if the Program has interactive interfaces that  do  not\n");
       fprintf(fp, "            display Appropriate Legal Notices, your work need not make them do so.\n\n");
       fprintf(fp, "        A  compilation  of  a covered work with other separate and independent works, which\n");
       fprintf(fp, "        are not by their nature extensions of the covered work, and which are not  combined\n");
       fprintf(fp, "        with  it  such  as  to  form  a  larger  program, in or on a volume of a storage or\n");
       fprintf(fp, "        distribution medium, is called an \"aggregate\" if the compilation and its  resulting\n");
       fprintf(fp, "        copyright  are  not  used  to limit the access or legal rights of the compilation's\n");
       fprintf(fp, "        users beyond what the individual works permit.  Inclusion of a covered work  in  an\n");
       fprintf(fp, "        aggregate does not cause this License to apply to the other parts of the aggregate.\n\n");
       fprintf(fp, "    6. Conveying Non-Source Forms.\n");
       fprintf(fp, "        You may convey a covered work in object code form under the terms of sections 4 and\n");
       fprintf(fp, "        5,  provided  that  you also convey the machine-readable Corresponding Source under\n");
       fprintf(fp, "        the terms of this License, in one of these ways:\n\n");
       fprintf(fp, "        a.  Convey the object code in, or embodied in,  a  physical  product  (including  a\n");
       fprintf(fp, "            physical distribution medium), accompanied by the Corresponding Source fixed on\n");
       fprintf(fp, "            a durable physical medium customarily used for software interchange.\n\n");
       fprintf(fp, "        b.  Convey  the  object  code  in,  or embodied in, a physical product (including a\n");
       fprintf(fp, "            physical distribution medium), accompanied by a written  offer,  valid  for  at\n");
       fprintf(fp, "            least  three  years  and valid for as long as you offer spare parts or customer\n");
       fprintf(fp, "            support for that product model, to give anyone who possesses  the  object  code\n");
       fprintf(fp, "            either  (1)  a  copy  of  the  Corresponding Source for all the software in the\n");
       fprintf(fp, "            product that  is  covered  by  this  License,  on  a  durable  physical  medium\n");
       fprintf(fp, "            customarily  used  for  software  interchange,  for  a  price no more than your\n");
       fprintf(fp, "            reasonable cost of physically performing  this  conveying  of  source,  or  (2)\n");
       fprintf(fp, "            access to copy the Corresponding Source from a network server at no charge.\n\n");
       fprintf(fp, "        c.  Convey individual copies of the object code with a copy of the written offer to\n");
       fprintf(fp, "            provide   the   Corresponding   Source.    This  alternative  is  allowed  only\n");
       fprintf(fp, "            occasionally and noncommercially, and only if you received the object code with\n");
       fprintf(fp, "            such an offer, in accord with subsection 6b.\n\n");
       fprintf(fp, "        d.  Convey the object code by offering access from a designated  place  (gratis  or\n");
       fprintf(fp, "            for  a  charge), and offer equivalent access to the Corresponding Source in the\n");
       fprintf(fp, "            same way through the same place at no further charge.   You  need  not  require\n");
       fprintf(fp, "            recipients to copy the Corresponding Source along with the object code.  If the\n");
       fprintf(fp, "            place to copy the object code is a network server, the Corresponding Source may\n");
       fprintf(fp, "            be  on  a  different  server  (operated  by you or a third party) that supports\n");
       fprintf(fp, "            equivalent copying facilities, provided you maintain clear directions  next  to\n");
       fprintf(fp, "            the  object  code saying where to find the Corresponding Source.  Regardless of\n");
       fprintf(fp, "            what server hosts the Corresponding Source, you remain obligated to ensure that\n");
       fprintf(fp, "            it is available for as long as needed to satisfy these requirements.\n\n");
       fprintf(fp, "        e.  Convey the object code using peer-to-peer  transmission,  provided  you  inform\n");
       fprintf(fp, "            other  peers  where  the  object  code and Corresponding Source of the work are\n");
       fprintf(fp, "            being offered to the general public at no charge under subsection 6d.\n\n");
       fprintf(fp, "        A separable portion of the object code, whose source  code  is  excluded  from  the\n");
       fprintf(fp, "        Corresponding  Source  as  a  System Library, need not be included in conveying the\n");
       fprintf(fp, "        object code work.\n\n");
       fprintf(fp, "        A \"User Product\" is either (1) a \"consumer  product\",  which  means  any  tangible\n");
       fprintf(fp, "        personal  property  which  is  normally  used  for  personal,  family, or household\n");
       fprintf(fp, "        purposes, or (2) anything designed or sold for incorporation into a  dwelling.   In\n");
       fprintf(fp, "        determining  whether  a  product  is  a  consumer  product, doubtful cases shall be\n");
       fprintf(fp, "        resolved in favor of coverage.  For a particular product received by  a  particular\n");
       fprintf(fp, "        user,  \"normally  used\" refers to a typical or common use of that class of product,\n");
       fprintf(fp, "        regardless of the status of the  particular  user  or  of  the  way  in  which  the\n");
       fprintf(fp, "        particular  user  actually  uses, or expects or is expected to use, the product.  A\n");
       fprintf(fp, "        product is a consumer product regardless of whether  the  product  has  substantial\n");
       fprintf(fp, "        commercial,  industrial  or  non-consumer uses, unless such uses represent the only\n");
       fprintf(fp, "        significant mode of use of the product.\n\n");
       fprintf(fp, "        \"Installation Information\" for  a  User  Product  means  any  methods,  procedures,\n");
       fprintf(fp, "        authorization  keys,  or other information required to install and execute modified\n");
       fprintf(fp, "        versions of a covered work in that User Product from  a  modified  version  of  its\n");
       fprintf(fp, "        Corresponding  Source.   The  information must suffice to ensure that the continued\n");
       fprintf(fp, "        functioning of the modified object code is in no case prevented or interfered  with\n");
       fprintf(fp, "        solely because modification has been made.\n\n");
       fprintf(fp, "        If  you  convey an object code work under this section in, or with, or specifically\n");
       fprintf(fp, "        for use in, a User Product, and the conveying occurs as part of  a  transaction  in\n");
       fprintf(fp, "        which  the  right  of  possession and use of the User Product is transferred to the\n");
       fprintf(fp, "        recipient in perpetuity or for a fixed term (regardless of how the  transaction  is\n");
       fprintf(fp, "        characterized),  the  Corresponding  Source  conveyed  under  this  section must be\n");
       fprintf(fp, "        accompanied by the Installation Information.  But this requirement does  not  apply\n");
       fprintf(fp, "        if  neither  you nor any third party retains the ability to install modified object\n");
       fprintf(fp, "        code on the User Product (for example, the work has been installed in ROM).\n\n");
       fprintf(fp, "        The requirement to provide Installation Information does not include a  requirement\n");
       fprintf(fp, "        to  continue  to  provide support service, warranty, or updates for a work that has\n");
       fprintf(fp, "        been modified or installed by the recipient, or for the User Product  in  which  it\n");
       fprintf(fp, "        has  been  modified  or  installed.   Access  to  a  network may be denied when the\n");
       fprintf(fp, "        modification itself materially and adversely affects the operation of  the  network\n");
       fprintf(fp, "        or violates the rules and protocols for communication across the network.\n\n");
       fprintf(fp, "        Corresponding  Source  conveyed,  and  Installation Information provided, in accord\n");
       fprintf(fp, "        with this section must be in a format that is  publicly  documented  (and  with  an\n");
       fprintf(fp, "        implementation  available  to  the public in source code form), and must require no\n");
       fprintf(fp, "        special password or key for unpacking, reading or copying.\n\n");
       fprintf(fp, "    7. Additional Terms.\n");
       fprintf(fp, "        \"Additional permissions\" are terms that supplement the terms  of  this  License  by\n");
       fprintf(fp, "        making  exceptions from one or more of its conditions.  Additional permissions that\n");
       fprintf(fp, "        are applicable to the entire Program shall be treated as though they were  included\n");
       fprintf(fp, "        in  this  License,  to  the  extent  that  they are valid under applicable law.  If\n");
       fprintf(fp, "        additional permissions apply only to part of the Program, that  part  may  be  used\n");
       fprintf(fp, "        separately under those permissions, but the entire Program remains governed by this\n");
       fprintf(fp, "        License without regard to the additional permissions.\n\n");
       fprintf(fp, "        When  you  convey  a  copy  of  a  covered  work, you may at your option remove any\n");
       fprintf(fp, "        additional permissions from that  copy,  or  from  any  part  of  it.   (Additional\n");
       fprintf(fp, "        permissions  may  be written to require their own removal in certain cases when you\n");
       fprintf(fp, "        modify the work.)  You may place additional permissions on material, added  by  you\n");
       fprintf(fp, "        to a covered work, for which you have or can give appropriate copyright permission.\n\n");
       fprintf(fp, "        Notwithstanding  any  other  provision  of  this License, for material you add to a\n");
       fprintf(fp, "        covered work, you may (if authorized by the copyright  holders  of  that  material)\n");
       fprintf(fp, "        supplement the terms of this License with terms:\n\n");
       fprintf(fp, "        a.  Disclaiming  warranty  or  limiting  liability  differently  from  the terms of\n");
       fprintf(fp, "            sections 15 and 16 of this License; or\n\n");
       fprintf(fp, "        b.  Requiring  preservation  of  specified  reasonable  legal  notices  or   author\n");
       fprintf(fp, "            attributions  in that material or in the Appropriate Legal Notices displayed by\n");
       fprintf(fp, "            works containing it; or\n\n");
       fprintf(fp, "        c.  Prohibiting misrepresentation of the origin of that material, or requiring that\n");
       fprintf(fp, "            modified versions of such material be marked in reasonable  ways  as  different\n");
       fprintf(fp, "            from the original version; or\n\n");
       fprintf(fp, "        d.  Limiting the use for publicity purposes of names of licensors or authors of the\n");
       fprintf(fp, "            material; or\n\n");
       fprintf(fp, "        e.  Declining  to  grant  rights  under  trademark law for use of some trade names,\n");
       fprintf(fp, "            trademarks, or service marks; or\n\n");
       fprintf(fp, "        f.  Requiring indemnification of licensors and authors of that material  by  anyone\n");
       fprintf(fp, "            who  conveys  the  material  (or  modified  versions  of  it)  with contractual\n");
       fprintf(fp, "            assumptions of liability  to  the  recipient,  for  any  liability  that  these\n");
       fprintf(fp, "            contractual assumptions directly impose on those licensors and authors.\n\n");
       fprintf(fp, "        All  other  non-permissive  additional  terms are considered \"further restrictions\"\n");
       fprintf(fp, "        within the meaning of section 10.  If the Program as you received it, or  any  part\n");
       fprintf(fp, "        of  it,  contains a notice stating that it is governed by this License along with a\n");
       fprintf(fp, "        term that is a further restriction,  you  may  remove  that  term.   If  a  license\n");
       fprintf(fp, "        document  contains a further restriction but permits relicensing or conveying under\n");
       fprintf(fp, "        this License, you may add to a covered work material governed by the terms of  that\n");
       fprintf(fp, "        license  document,  provided  that  the  further  restriction does not survive such\n");
       fprintf(fp, "        relicensing or conveying.\n\n");
       fprintf(fp, "        If you add terms to a covered work in accord with this section, you must place,  in\n");
       fprintf(fp, "        the  relevant source files, a statement of the additional terms that apply to those\n");
       fprintf(fp, "        files, or a notice indicating where to find the applicable terms.\n\n");
       fprintf(fp, "        Additional terms, permissive or non-permissive, may be stated  in  the  form  of  a\n");
       fprintf(fp, "        separately  written  license, or stated as exceptions; the above requirements apply\n");
       fprintf(fp, "        either way.\n\n");
       fprintf(fp, "    8. Termination.\n");
       fprintf(fp, "        You may not propagate or modify a covered work except as expressly  provided  under\n");
       fprintf(fp, "        this  License.   Any  attempt otherwise to propagate or modify it is void, and will\n");
       fprintf(fp, "        automatically terminate your  rights  under  this  License  (including  any  patent\n");
       fprintf(fp, "        licenses granted under the third paragraph of section 11).\n\n");
       fprintf(fp, "        However,  if  you  cease  all  violation  of this License, then your license from a\n");
       fprintf(fp, "        particular copyright holder is reinstated (a) provisionally, unless and  until  the\n");
       fprintf(fp, "        copyright   holder   explicitly  and  finally  terminates  your  license,  and  (b)\n");
       fprintf(fp, "        permanently, if the copyright holder fails to notify you of the violation  by  some\n");
       fprintf(fp, "        reasonable means prior to 60 days after the cessation.\n\n");
       fprintf(fp, "        Moreover, your license from a particular copyright holder is reinstated permanently\n");
       fprintf(fp, "        if  the  copyright  holder  notifies you of the violation by some reasonable means,\n");
       fprintf(fp, "        this is the first time you have received notice of violation of this  License  (for\n");
       fprintf(fp, "        any  work)  from that copyright holder, and you cure the violation prior to 30 days\n");
       fprintf(fp, "        after your receipt of the notice.\n\n");
       fprintf(fp, "        Termination of your rights under this section does not terminate  the  licenses  of\n");
       fprintf(fp, "        parties  who  have  received copies or rights from you under this License.  If your\n");
       fprintf(fp, "        rights have been terminated and not permanently reinstated, you do not  qualify  to\n");
       fprintf(fp, "        receive new licenses for the same material under section 10.\n\n");
       fprintf(fp, "    9. Acceptance Not Required for Having Copies.\n");
       fprintf(fp, "        You  are  not  required to accept this License in order to receive or run a copy of\n");
       fprintf(fp, "        the Program.  Ancillary propagation  of  a  covered  work  occurring  solely  as  a\n");
       fprintf(fp, "        consequence  of using peer-to-peer transmission to receive a copy likewise does not\n");
       fprintf(fp, "        require acceptance.  However, nothing other than this License grants you permission\n");
       fprintf(fp, "        to propagate or modify any covered work.  These actions infringe copyright  if  you\n");
       fprintf(fp, "        do not accept this License.  Therefore, by modifying or propagating a covered work,\n");
       fprintf(fp, "        you indicate your acceptance of this License to do so.\n\n");
       fprintf(fp, "    10. Automatic Licensing of Downstream Recipients.\n");
       fprintf(fp, "        Each time you convey a covered work, the recipient automatically receives a license\n");
       fprintf(fp, "        from  the  original  licensors,  to run, modify and propagate that work, subject to\n");
       fprintf(fp, "        this License.  You are not responsible for enforcing compliance  by  third  parties\n");
       fprintf(fp, "        with this License.\n\n");
       fprintf(fp, "        An  \"entity  transaction\" is a transaction transferring control of an organization,\n");
       fprintf(fp, "        or substantially all assets of one, or  subdividing  an  organization,  or  merging\n");
       fprintf(fp, "        organizations.    If   propagation  of  a  covered  work  results  from  an  entity\n");
       fprintf(fp, "        transaction, each party to that transaction who receives a copy of  the  work  also\n");
       fprintf(fp, "        receives  whatever  licenses to the work the party's predecessor in interest had or\n");
       fprintf(fp, "        could give under the  previous  paragraph,  plus  a  right  to  possession  of  the\n");
       fprintf(fp, "        Corresponding  Source  of  the  work  from  the  predecessor  in  interest,  if the\n");
       fprintf(fp, "        predecessor has it or can get it with reasonable efforts.\n\n");
       fprintf(fp, "        You may not impose any further restrictions on the exercise of the  rights  granted\n");
       fprintf(fp, "        or  affirmed  under  this  License.  For example, you may not impose a license fee,\n");
       fprintf(fp, "        royalty, or other charge for exercise of rights granted under this License, and you\n");
       fprintf(fp, "        may not initiate litigation (including a cross-claim or counterclaim in a  lawsuit)\n");
       fprintf(fp, "        alleging that any patent claim is infringed by making, using, selling, offering for\n");
       fprintf(fp, "        sale, or importing the Program or any portion of it.\n\n");
       fprintf(fp, "    11. Patents.\n");
       fprintf(fp, "        A  \"contributor\" is a copyright holder who authorizes use under this License of the\n");
       fprintf(fp, "        Program or a work on which the Program is based.  The work thus licensed is  called\n");
       fprintf(fp, "        the contributor's \"contributor version\".\n\n");
       fprintf(fp, "        A contributor's \"essential patent claims\" are all patent claims owned or controlled\n");
       fprintf(fp, "        by  the  contributor, whether already acquired or hereafter acquired, that would be\n");
       fprintf(fp, "        infringed by some manner, permitted by this License, of making, using,  or  selling\n");
       fprintf(fp, "        its  contributor version, but do not include claims that would be infringed only as\n");
       fprintf(fp, "        a consequence of further modification of the contributor version.  For purposes  of\n");
       fprintf(fp, "        this  definition,  \"control\"  includes  the  right to grant patent sublicenses in a\n");
       fprintf(fp, "        manner consistent with the requirements of this License.\n\n");
       fprintf(fp, "        Each contributor grants you a non-exclusive, worldwide, royalty-free patent license\n");
       fprintf(fp, "        under the contributor's essential patent claims, to  make,  use,  sell,  offer  for\n");
       fprintf(fp, "        sale,  import  and  otherwise  run,  modify  and  propagate  the  contents  of  its\n");
       fprintf(fp, "        contributor version.\n\n");
       fprintf(fp, "        In the following three paragraphs, a \"patent license\" is any express  agreement  or\n");
       fprintf(fp, "        commitment,  however  denominated,  not  to  enforce  a  patent (such as an express\n");
       fprintf(fp, "        permission to practice a patent or covenant not to sue  for  patent  infringement).\n");
       fprintf(fp, "        To  \"grant\"  such  a  patent  license to a party means to make such an agreement or\n");
       fprintf(fp, "        commitment not to enforce a patent against the party.\n\n");
       fprintf(fp, "        If you convey a covered work, knowingly  relying  on  a  patent  license,  and  the\n");
       fprintf(fp, "        Corresponding  Source  of  the  work  is  not available for anyone to copy, free of\n");
       fprintf(fp, "        charge and under the terms of this License, through a  publicly  available  network\n");
       fprintf(fp, "        server  or  other  readily  accessible  means,  then  you must either (1) cause the\n");
       fprintf(fp, "        Corresponding Source to be so available, or (2) arrange to deprive yourself of  the\n");
       fprintf(fp, "        benefit of the patent license for this particular work, or (3) arrange, in a manner\n");
       fprintf(fp, "        consistent  with  the requirements of this License, to extend the patent license to\n");
       fprintf(fp, "        downstream recipients.  \"Knowingly relying\" means you have actual  knowledge  that,\n");
       fprintf(fp, "        but  for  the patent license, your conveying the covered work in a country, or your\n");
       fprintf(fp, "        recipient's use of the covered work in  a  country,  would  infringe  one  or  more\n");
       fprintf(fp, "        identifiable patents in that country that you have reason to believe are valid.\n\n");
       fprintf(fp, "        If,  pursuant  to  or  in  connection with a single transaction or arrangement, you\n");
       fprintf(fp, "        convey, or propagate by procuring conveyance of, a covered work, and grant a patent\n");
       fprintf(fp, "        license to some of the parties receiving the covered work authorizing them to  use,\n");
       fprintf(fp, "        propagate,  modify  or  convey a specific copy of the covered work, then the patent\n");
       fprintf(fp, "        license you grant is automatically extended to all recipients of the  covered  work\n");
       fprintf(fp, "        and works based on it.\n\n");
       fprintf(fp, "        A patent license is \"discriminatory\" if it does not include within the scope of its\n");
       fprintf(fp, "        coverage,  prohibits  the exercise of, or is conditioned on the non-exercise of one\n");
       fprintf(fp, "        or more of the rights that are specifically granted under this  License.   You  may\n");
       fprintf(fp, "        not  convey  a covered work if you are a party to an arrangement with a third party\n");
       fprintf(fp, "        that is in the business of distributing software, under which you make  payment  to\n");
       fprintf(fp, "        the  third  party  based  on the extent of your activity of conveying the work, and\n");
       fprintf(fp, "        under which the third party grants, to any of the parties  who  would  receive  the\n");
       fprintf(fp, "        covered  work  from  you,  a  discriminatory  patent license (a) in connection with\n");
       fprintf(fp, "        copies of the covered work conveyed by you (or copies made from those  copies),  or\n");
       fprintf(fp, "        (b)  primarily  for  and  in connection with specific products or compilations that\n");
       fprintf(fp, "        contain the covered work, unless you entered into that arrangement, or that  patent\n");
       fprintf(fp, "        license was granted, prior to 28 March 2007.\n\n");
       fprintf(fp, "        Nothing  in  this  License  shall be construed as excluding or limiting any implied\n");
       fprintf(fp, "        license or other defenses to infringement that may otherwise be  available  to  you\n");
       fprintf(fp, "        under applicable patent law.\n\n");
       fprintf(fp, "    12. No Surrender of Others' Freedom.\n");
       fprintf(fp, "        If  conditions  are imposed on you (whether by court order, agreement or otherwise)\n");
       fprintf(fp, "        that contradict the conditions of this License, they do not  excuse  you  from  the\n");
       fprintf(fp, "        conditions  of  this License.  If you cannot convey a covered work so as to satisfy\n");
       fprintf(fp, "        simultaneously  your  obligations  under  this  License  and  any  other  pertinent\n");
       fprintf(fp, "        obligations,  then  as a consequence you may not convey it at all.  For example, if\n");
       fprintf(fp, "        you agree to terms that obligate you to collect a  royalty  for  further  conveying\n");
       fprintf(fp, "        from  those  to  whom  you  convey the Program, the only way you could satisfy both\n");
       fprintf(fp, "        those terms and this License would  be  to  refrain  entirely  from  conveying  the\n");
       fprintf(fp, "        Program.\n\n");
       fprintf(fp, "    13. Use with the GNU Affero General Public License.\n");
       fprintf(fp, "        Notwithstanding any other provision of this License, you have permission to link or\n");
       fprintf(fp, "        combine  any  covered  work  with a work licensed under version 3 of the GNU Affero\n");
       fprintf(fp, "        General Public License into a single combined work, and  to  convey  the  resulting\n");
       fprintf(fp, "        work.   The  terms  of this License will continue to apply to the part which is the\n");
       fprintf(fp, "        covered work, but the  special  requirements  of  the  GNU  Affero  General  Public\n");
       fprintf(fp, "        License,  section  13,  concerning  interaction through a network will apply to the\n");
       fprintf(fp, "        combination as such.\n\n");
       fprintf(fp, "    14. Revised Versions of this License.\n");
       fprintf(fp, "        The Free Software Foundation may publish revised and/or new  versions  of  the  GNU\n");
       fprintf(fp, "        General  Public  License  from  time to time.  Such new versions will be similar in\n");
       fprintf(fp, "        spirit to the present version, but may differ in detail to address new problems  or\n");
       fprintf(fp, "        concerns.\n\n");
       fprintf(fp, "        Each  version  is  given a distinguishing version number.  If the Program specifies\n");
       fprintf(fp, "        that a certain numbered version of the GNU General Public  License  \"or  any  later\n");
       fprintf(fp, "        version\"  applies  to it, you have the option of following the terms and conditions\n");
       fprintf(fp, "        either of that numbered version or of any  later  version  published  by  the  Free\n");
       fprintf(fp, "        Software  Foundation.   If the Program does not specify a version number of the GNU\n");
       fprintf(fp, "        General Public License, you may choose any  version  ever  published  by  the  Free\n");
       fprintf(fp, "        Software Foundation.\n\n");
       fprintf(fp, "        If  the  Program specifies that a proxy can decide which future versions of the GNU\n");
       fprintf(fp, "        General Public License can be used, that proxy's public statement of acceptance  of\n");
       fprintf(fp, "        a version permanently authorizes you to choose that version for the Program.\n\n");
       fprintf(fp, "        Later  license versions may give you additional or different permissions.  However,\n");
       fprintf(fp, "        no additional obligations are imposed on any author or copyright holder as a result\n");
       fprintf(fp, "        of your choosing to follow a later version.\n\n");
       fprintf(fp, "    15. Disclaimer of Warranty.\n");
       fprintf(fp, "        THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED  BY  APPLICABLE  LAW.\n");
       fprintf(fp, "        EXCEPT  WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES\n");
       fprintf(fp, "        PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY  OF  ANY  KIND,  EITHER  EXPRESSED  OR\n");
       fprintf(fp, "        IMPLIED,  INCLUDING,  BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\n");
       fprintf(fp, "        AND FITNESS FOR A PARTICULAR PURPOSE.  THE  ENTIRE  RISK  AS  TO  THE  QUALITY  AND\n");
       fprintf(fp, "        PERFORMANCE  OF  THE  PROGRAM IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU\n");
       fprintf(fp, "        ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n\n");
       fprintf(fp, "    16. Limitation of Liability.\n");
       fprintf(fp, "        IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED  TO  IN  WRITING  WILL  ANY\n");
       fprintf(fp, "        COPYRIGHT  HOLDER,  OR  ANY  OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS\n");
       fprintf(fp, "        PERMITTED ABOVE, BE LIABLE TO YOU FOR  DAMAGES,  INCLUDING  ANY  GENERAL,  SPECIAL,\n");
       fprintf(fp, "        INCIDENTAL  OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE\n");
       fprintf(fp, "        PROGRAM (INCLUDING BUT  NOT  LIMITED  TO  LOSS  OF  DATA  OR  DATA  BEING  RENDERED\n");
       fprintf(fp, "        INACCURATE  OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM\n");
       fprintf(fp, "        TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER  PARTY  HAS  BEEN\n");
       fprintf(fp, "        ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\n");
       fprintf(fp, "    17. Interpretation of Sections 15 and 16.\n");
       fprintf(fp, "        If  the disclaimer of warranty and limitation of liability provided above cannot be\n");
       fprintf(fp, "        given local legal effect according to their terms,  reviewing  courts  shall  apply\n");
       fprintf(fp, "        local  law that most closely approximates an absolute waiver of all civil liability\n");
       fprintf(fp, "        in connection with the Program,  unless  a  warranty  or  assumption  of  liability\n");
       fprintf(fp, "        accompanies a copy of the Program in return for a fee.\n\n");
       fprintf(fp, "END OF TERMS AND CONDITIONS\n");
       fprintf(fp, "How to Apply These Terms to Your New Programs\n");
       fprintf(fp, "    If you develop a new program, and you want it to be of the greatest possible use to the\n");
       fprintf(fp, "    public,  the  best  way  to achieve this is to make it free software which everyone can\n");
       fprintf(fp, "    redistribute and change under these terms.\n\n");
       fprintf(fp, "    To do so, attach the following notices to the program.  It is safest to attach them  to\n");
       fprintf(fp, "    the  start of each source file to most effectively state the exclusion of warranty; and\n");
       fprintf(fp, "    each file should have at least the \"copyright\" line and a pointer  to  where  the  full\n");
       fprintf(fp, "    notice is found.\n\n");
       fprintf(fp, "            <one line to give the program's name and a brief idea of what it does.>\n");
       fprintf(fp, "            Copyright (C) <year> <name of author>\n\n");
       fprintf(fp, "            This program is free software: you can redistribute it and/or modify\n");
       fprintf(fp, "            it under the terms of the GNU General Public License as published by\n");
       fprintf(fp, "            the Free Software Foundation, either version 3 of the License, or (at\n");
       fprintf(fp, "            your option) any later version.\n\n");
       fprintf(fp, "            This program is distributed in the hope that it will be useful, but\n");
       fprintf(fp, "            WITHOUT ANY WARRANTY; without even the implied warranty of\n");
       fprintf(fp, "            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n");
       fprintf(fp, "            General Public License for more details.\n\n");
       fprintf(fp, "            You should have received a copy of the GNU General Public License\n");
       fprintf(fp, "            along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\n");
       fprintf(fp, "    Also add information on how to contact you by electronic and paper mail.\n\n");
       fprintf(fp, "    If  the program does terminal interaction, make it output a short notice like this when\n");
       fprintf(fp, "    it starts in an interactive mode:\n\n");
       fprintf(fp, "            <program> Copyright (C) <year> <name of author>\n");
       fprintf(fp, "            This program comes with ABSOLUTELY NO WARRANTY; for details type \"show w\".\n");
       fprintf(fp, "            This is free software, and you are welcome to redistribute it\n");
       fprintf(fp, "            under certain conditions; type \"show c\" for details.\n\n");
       fprintf(fp, "    The hypothetical commands show w and show c should show the appropriate  parts  of  the\n");
       fprintf(fp, "    General  Public  License.  Of course, your program's commands might be different; for a\n");
       fprintf(fp, "    GUI interface, you would use an \"about box\".\n\n");
       fprintf(fp, "    You should also get your employer (if you work as a programmer) or school, if  any,  to\n");
       fprintf(fp, "    sign  a  \"copyright disclaimer\" for the program, if necessary.  For more information on\n");
       fprintf(fp, "    this, and how to apply and follow the GNU GPL, see <https://www.gnu.org/licenses/>.\n\n");
       fprintf(fp, "    The GNU General  Public  License  does  not  permit  incorporating  your  program  into\n");
       fprintf(fp, "    proprietary  programs.   If  your  program is a subroutine library, you may consider it\n");
       fprintf(fp, "    more useful to permit linking proprietary applications with the library.   If  this  is\n");
       fprintf(fp, "    what you want to do, use the GNU Lesser General Public License instead of this License. \n");
       fprintf(fp, "    But first, please read <https://www.gnu.org/licenses/why-not-lgpl.html>.                \n");
}
#endif
